init:
	cd envs/dev && terraform init

fmt:
	terraform fmt -recursive

validate:
	cd envs/dev && terraform validate

plan:
	cd envs/dev && terraform plan

apply:
	cd envs/dev && terraform apply -auto-approve

destroy:
	cd envs/dev && terraform destroy -auto-approve